### ISSUE TITLE
Visual artifacts and glitches

### ISSUE THREAD

**Issue by speachy** [garglk/garglk#434] opened 2021-05-25 02:20 UTC
I hope this is a case of PEBKAC, but ever since the port to GTK3 landed (commit 9a283b1734c1fd279da19b27c948ba458560b90d) garglk has been unusable for me:

 * No window decorations (titlebar, window borders, resize handles, can't move window, etc)
 * Scrolling/repainting artifacts (outer edge of window is not repainted properly when scrolling, leading to artifacts)
 * Typed text does not appear until enter is pressed

This seems to happen regardless of which engine is used (zcode, tads, adrift)

I'm compiling from source, running on Fedora 34 (Gnome 40, GTK 3.24.29, Wayland)

Thanks!

**Comment by speachy** [comment] 2021-05-26 02:06
![Screenshot from 2021-05-25 22-01-18](https://user-images.githubusercontent.com/5199155/119591591-e3426e80-bda4-11eb-9536-acd7f0c704e3.png)

Here's an example, running I-0.z5.  Launch, press any key to continue, and it's clear the scrolling/pagination is shot.  Plus the lack of window decoration.  garlglk freshly compiled from today's sources.

**Comment by Tynach** [comment] 2021-05-26 02:09
I don't have that issue, but I'm using KDE Neon. I do know that Gnome, when running GTK apps at least, sometimes assumes that the GTK apps themselves are going to draw their own window decorations. Perhaps it's detecting the app uses GTK3 and makes that assumption?

Does Qalculate also fail to draw window decorations? It's a GTK3 app that doesn't typically draw its own window decorations, at least on KDE and such; maybe it's smarter about that and draws it under Gnome, though.

**Comment by speachy** [comment] 2021-05-26 15:31
I think the problem is that newer versions of GTK3 (3.12, ~2015) default to using client-side decorations.  When running under a native GTK-based desktop (ie gnome) the desktop expects the application to handle all of that stuff.  When running standalone, the decorations end up provided by the system.

**Comment by Tynach** [comment] 2021-05-26 18:05
@speachy, does it also happen in KDE under wayland?

**Comment by speachy** [comment] 2021-05-26 18:39
I don't have any systems with KDE installed; the best I could do is spin up a VM and see what happens, but I'm not likely to have the bandwidth for that for a few days.

**Comment by Tynach** [comment] 2021-05-27 16:27
@speachy, understandable. I just don't know of any other non-GTK Wayland compositors that for sure default to server-side decorations. Thankfully, a minimalist KDE installation is a lot lighter weight these days than in the past. Should just need to install something like `plasma-workspace` and `plasma-workspace-wayland` and their dependencies; at least, that's what the packages on KDE Neon (and I presume various Debian and Ubuntu derivatives) are called.

If I remember correctly, such a basic installation doesn't even include a text editor, or if it does, it'd be the stripped down KWrite.

**Comment by cspiegel** [comment] 2021-06-04 16:08
@speachy Can you try https://github.com/PCMan/gtk3-nocsd and see if launching through that brings back the titlebar?  I don't have Gnome (or any gtk desktop) so I can't reproduce this.  If the nocsd hack works, maybe it can be directly implemented by Gargoyle.

Though the real solution is a port to Qt.  Maybe that ought to be accelerated in light of gtk3's brokenness.

**Comment by speachy** [comment] 2021-06-04 19:59
@cspiegel I tried gtk3-nocsd and it seemed to have no discernable effect.

**Comment by Tynach** [comment] 2021-06-05 07:20
@cspiegel, do we really need either GTK *or* Qt? It seems to me that since all the drawing is done manually onto a blank canvas, it'd be possible to port to something like SDL2 instead - especially since it's already a dependency. For the open file dialog, we could use xdg-desktop-portal so that KDE users will see a Qt file dialog, and Gnome users will see a GTK file dialog. That's what Firefox and I believe Chrome do these days.

@speachy, I've tried Gargoyle in KDE under a wayland session, and didn't experience any of the issues you've described/screenshotted. Could be either a Gnome issue, or maybe something weird with your GPU (or drivers)? What sort of GPU do you have?

Also, I've found some GTK applications break in weird ways when I use `xim` as my input method. I presume this isn't the case here since you're on Wayland, but maybe it's another direction to look at this from.

**Comment by speachy** [comment] 2021-06-05 12:29
@Tynach, Both machines I'm able to test this on are similar (Fedora 34, GNOME+Wayland) and have AMD GPUs using F/OSS Mesa drivers.  (Though one is an iGPU and the other is discrete)  The general software configuration is also similar.  I was intending to try this with a stock, unmodified system in a VM.

FWIW, I think your remark about using a native SDL2 window/surface makes a lot of sense, but I suspect the ancillary features GTK/QT provides matter more than we think (input methods, assistative technologies, etc)

**Comment by speachy** [comment] 2021-06-05 13:53
Additional data points: The Fedora 34 KDE spin works great, window decorations and no scrolling artifacts, but stock Fedora 34 GNOME malfunctions the same way.  Both running in a VM.

Interesting detail -- the file chooser has proper window decorations.

**Comment by Tynach** [comment] 2021-06-05 19:42
@speachy, yeah, the file picker implements its own window decorations, because it's a GTK app that uses client-side decorations. It probably has the same decorations on both KDE and Gnome, rather than using KDE's decorations on KDE (though it'll likely use the Breeze GTK theme so it'll look similar, it won't have a dedicated titlebar; instead still having the menu button and other elements directly in its own self-drawn title bar).

Actually, I do see one bug here in KDE Neon relating to Wayland. It only uses a black mouse cursor, and the black mouse doesn't change to a pointing hand when hovering over links. So there are some Wayland bugs even on KDE, but they're much less severe.

**Comment by cspiegel** [comment] 2021-06-06 15:15
> @cspiegel, do we really need either GTK _or_ Qt? It seems to me that since all the drawing is done manually onto a blank canvas, it'd be possible to port to something like SDL2 instead - especially since it's already a dependency. For the open file dialog, we could use xdg-desktop-portal so that KDE users will see a Qt file dialog, and Gnome users will see a GTK file dialog. That's what Firefox and I believe Chrome do these days.

That's certainly a possibility worth exploring.  Using Qt does allow for the possibility of eventually scrapping the custom Windows and Mac code, since Qt is cross-platform, and as you note, since Gargoyle doesn't actually use any widgets, some of the concerns of looking non-native don't really matter: I believe Qt _does_ use native file pickers, so the only place the toolkits' visual elements are used would still look native.

Another question, though, is how portable xdg-desktop-portal is.  Gargoyle at least nominally supports the BSDs, and I'm not sure how well xdg-desktop-portal is supported there.

Ultimately, for the next release (which really ought to come soon), the missing window decorations need to be fixed, so even a stop-gap solution would be better than what exists currently.

**Comment by Tynach** [comment] 2021-06-07 03:49
> That's certainly a possibility worth exploring. Using Qt does allow for the possibility of eventually scrapping the custom Windows and Mac code, since Qt is cross-platform, and as you note, since Gargoyle doesn't actually use any widgets, some of the concerns of looking non-native don't really matter: I believe Qt _does_ use native file pickers, so the only place the toolkits' visual elements are used would still look native.

Qt does not use native file pickers, at least not as far as the various desktop environments on Linux go. In Gnome it might use a theme that tries to mimic the current GTK theme, or it might use its default 'Fusion' theme instead; and either way, it won't use Gnome's file picker (which is what Gargoyle currently uses, at least on Linux).

It's worth noting that Qt's standard file picker (QFileDialog) is not the same as KDE's, and offers significantly less functionality than KDE's own file picker. Using xdg-desktop-portal will give Gnome users the Gnome file picker (absolutely no change for them from the current code), and will give Plasma users KDE's file picker.

> Another question, though, is how portable xdg-desktop-portal is. Gargoyle at least nominally supports the BSDs, and I'm not sure how well xdg-desktop-portal is supported there.

It's true that xdg-desktop-portal not portable to Windows or Mac OS, at least as far as I'm aware. And I'm getting mixed results when looking up screenshots of QFileDialog on Windows/Mac OS; sometimes I see what I expect (the standard, somewhat bare-bones file dialog window I see in non-KDE Qt applications here on Linux, but with Windows-themed widgets and title bar), and other times I see a native Windows file picking dialog box. I don't know if I'm just getting pictures of file dialog boxes in general or not, and it doesn't help that a lot of the results from Google Images are not in English.

With BSD... I don't know. It looks like using `GtkFileChooserNative` is meant to use xdg-desktop-portal transparently, and is how Firefox uses it. I found that out just now while trying to find BSD-relevant results, finding [this thread][bsd] from 2019. This kinda negates getting rid of GTK as a dependency though as it's literally a GTK call. Heh. Overall, the end result seems to be a 'maybe', along with a lot of confused shrugging from all sides. Optimistically, I think the worst case scenario is 'eventually'. Pessimistically, the worst case scenario is 'nobody else cares about BSD enough for it to ever actually happen, until minutes before the sun expands, engulfing the Earth in a huge fireball and making the whole thing moot'.

I also found [this pull request][pr] for FreeBSD support in the `xdg-desktop-portal` project proper, but I don't know how relevant this is. It might be that FreeBSD packages have the changes in their packages already. There doesn't seem to be much discussion about it, or reasons given why it hasn't been merged yet.

> Ultimately, for the next release (which really ought to come soon), the missing window decorations need to be fixed, so even a stop-gap solution would be better than what exists currently.

Agreed, maybe along with the mouse cursor issues (though that sounds lower priority).

@speachy, would you be able to build [Qalculate GTK] (and its dependency [libqalculate]), and see how it behaves? It's a GTK3 application that, on KDE at least, uses KWin's own window decorations instead of drawing its own client-side ones. I'm curious if it switches to using client-side decorations when used within Gnome, or if it somehow tells Gnome to give it window decorations, or what. Might also tell you if it's a problem with your (or Fedora's) specific libraries/configuration, vs. a problem with the code itself.

[bsd]: http://freebsd.1045724.x6.nabble.com/Firefox-GtkFileChooserNative-file-selection-dialogues-td6350434.html
[pr]: https://github.com/flatpak/xdg-desktop-portal/pull/532
[Qalculate GTK]: https://github.com/Qalculate/qalculate-gtk
[libqalculate]: https://github.com/Qalculate/libqalculate

**Comment by speachy** [comment] 2021-06-07 11:36
One other data point -- over the weekend I was doing some experimentation.  if I add a call to gtk_window_set_decorated(GTK_WINDOW(frame), FALSE) in winopen() the visual gitches (scrolling, typing visible) go away completely, but the window remains undecorated.  So while not ideal, but it's at least usable!

I _think_ the reason for this problem that garglk is not using GTK as it's intended -- ie we're just creating a standalone window that's not part of a "GApplication"  but the CSD stuff is set up somewhere in the bowels GApplication setup/window initialization.  I'm sure it's possible to fix this up manually but it's going to take more digging.

**Comment by cspiegel** [comment] 2021-06-07 14:45
> Qt does not use native file pickers, at least not as far as the various desktop environments on Linux go. In Gnome it might use a theme that tries to mimic the current GTK theme, or it might use its default 'Fusion' theme instead; and either way, it won't use Gnome's file picker (which is what Gargoyle currently uses, at least on Linux).

I meant on Windows and macOS; it's important that, on those operating systems, the dialogs look native.  There's no native toolkit on the Unixes, but of course, as you say, you can try to use something that matches the current desktop.  Bear in mind, though, that Gargoyle's last release still used Gtk2, so no official releases have matched anybody's desktop for years.  I'm less concerned about something looking non-native on Linux since that's been par for the course since the dawn of time; especially so if the upside (one UI system to maintain instead of 3) is so huge.

However!  It looks like Qt5 can use Gtk3's file picker.  Set the environment variable `QT_QPA_PLATFORMTHEME` to `gtk3` and run a Qt program.  The widgets (which Gargoyle doesn't use) won't be Gtk3, of course, but the file pickers are.  I don't know if any Gtk-based desktops set this variable, but at this point it looks like Qt5 provides everything needed to integrate into Gtk, and so the onus is on Gtk desktops to do the right thing.

> It's worth noting that Qt's standard file picker (QFileDialog) is not the same as KDE's, and offers significantly less functionality than KDE's own file picker. Using xdg-desktop-portal will give Gnome users the Gnome file picker (absolutely no change for them from the current code), and will give Plasma users KDE's file picker.

On my system, at least, pure Qt programs _do_ use KDE's file picker when running under KDE.  Qt looks at various environment variables to determine which desktop it's running under, and sets its platform theme accordingly (which leads me to believe it will use the Gtk3 platform theme automatically on Gtk desktops, but I can't test that).

Qt will use the following to determine if KDE is running:
  * XDG_CURRENT_DESKTOP
  * KDE_FULL_SESSION
  * DESKTOP_SESSION

If none of these imply KDE, it'll use its own picker, KDE's otherwise.

Qt does all this through platform themes, so it's possible that a distribution might not include all platform themes, or might make them separate packages to install, but it looks like Qt works hard to integrate into desktops.

> Overall, the end result seems to be a 'maybe', along with a lot of confused shrugging from all sides

I know the BSDs tend to be very reluctant to include ideas that originated on Linux; this is partly just kneejerk, but they are also understandably concerned about including large chunks of new code that haven't necessarily been vetted to their standards, and that they had no hand in designing.  As small as the BSD userbase is, there's no real reason to exclude them over something that's ultimately cosmetic.

**Comment by cspiegel** [comment] 2021-06-07 14:46
> One other data point -- over the weekend I was doing some experimentation. if I add a call to gtk_window_set_decorated(GTK_WINDOW(frame), FALSE) in winopen() the visual gitches (scrolling, typing visible) go away completely, but the window remains undecorated. So while not ideal, but it's at least usable!

If you want to create a pull request with that change, I'll get it merged in.  No question that a partial fix is better than none at all!

**Comment by speachy** [comment] 2021-06-08 02:52
@cspiegel  see PR#438 for the minimal change.

**Comment by cspiegel** [comment] 2021-06-08 04:29
> @cspiegel see PR#438 for the minimal change.

Merged, thank you!

**Comment by cspiegel** [comment] 2021-06-09 05:00
Well, I had to revert that last change because it broke things on non-Gnome desktops.

I'm going to really start looking into getting Qt working.

**Comment by speachy** [comment] 2021-06-09 12:15
That's disappointing, but not unexpected.

**Comment by Tynach** [comment] 2021-06-10 10:38
@speachy, it might be a Gnome or GTK bug. Maybe file a bug report with them?

**Comment by speachy** [comment] 2021-06-10 11:42
I tried asking for help in gnome's #gtk irc channel.  Initial responses include:

that could be just about anything"
"try removing gtk_widget_set_events call"   (which I tried, to no effect)
"keep GTKWindow as vanilla as possible" 
"not properly processing events or doing invalidation wrong could cause any number of these problems"
"you're using GTK like a container tp put whatever else into it, which is... not how GTK works"

I'm trying to strip away stuff to see what happens.

**Comment by speachy** [comment] 2021-06-10 12:56
Ok, I've found the underlying problems:

First, we're painting directly into the frame rather than the canvas.  That is easily fixed, but it uncovers a second problem.

Secondly,  we assume that the canvas size is the same as the window size. This is true under X11, but not under Wayland w/CSD, causing us to partially paint over (and steal events from) the CSD decorations in the window.  This can be worked around in the short term by forcing GTK to use the x11 backend  (by setting GDK_BACKEND=x11)

I'll send in a PR to fix the first issue now, and I'll keep working on the second.

**Comment by speachy** [comment] 2021-06-10 13:42
#442 resolves all of these issues, as best as I can tell.  Completely untested under non-Gnome.

**Comment by cspiegel** [comment] 2021-06-11 19:09
I finally put the effort in to get my Qt branch working, and it seems to be in pretty good shape. There's a draft request at #443 that could use some testing.

In addition to my main system, I've tested on FreeBSD, Ubuntu Linux, and Arch Linux.  But extra testing would be helpful.

**Comment by cspiegel** [comment] 2021-06-15 22:09
I've merged the Qt branch into master.  I can't test on Gnome, but hopefully it addresses the issues noted here.

**Comment by speachy** [comment] 2021-06-15 22:21
master isn't linking properly (have to use g++ rather than gcc to do the linking), but after I fix that manually, this is the result:

$ gargoyle I-0.z5 || echo FAIL $?
QSocketNotifier: Can only be used with threads started with QThread
FAIL 1

(using QT 5.15.2)

If I run it without a story file, a file chooser pops up, and then it crashes with that error after selecting one.

**Comment by cspiegel** [comment] 2021-06-16 00:20
> `master isn't linking properly (have to use g++ rather than gcc to do the linking)`

I (briefly) noted in the pull request that due to Jam issues (well, probably Gargoyle's use of Jam), you have to explicitly specify the C++ compiler using `-sC++=g++` (or clang++, whatever), since Jam sets `C++` to `cc` by default (why? Don't ask me...)  This is a temporary hiccup till CMake support lands.  I should have made it more clear how to build it in the interim.

> $ gargoyle I-0.z5 || echo FAIL $?
> QSocketNotifier: Can only be used with threads started with QThread
> FAIL 1

Interesting.  I'll install a VM with Fedora and give it a spin.  I haven't seen that error message at all.  I wonder if it's part of the gtk platform support in Qt.

Thank you for testing!

**Comment by cspiegel** [comment] 2021-06-16 01:40
@speachy When you say it crashes, does that mean that the interpreter doesn't launch, or is there a segfault/abort?  Do you see a "Couldn't start terp" message?  It sounds like it just exits with an exit code of 1, and does nothing else; is that correct?

I can reproduce that "QSocketNotifier" message on Fedora, but everyting still works for me, as it apparently does on one of your systems.  That message is apparently related to Wayland.  If you set the environment variable `$QT_QPA_PLATFORM` to `xcb`, does it work?

There is one place, I think, where the gargoyle binary will exit with value 1 without showing an error message: if it finds an interpreter, and runs it, but it exits with a non-zero value (basically, it passes through the exit code of the interpreter process).  So can you try directly running one of the interpreters?  For I-0, you can directly call bocfel with it and see if it starts up.

**Comment by cspiegel** [comment] 2021-06-16 04:19
Some more testing indicates that this is not specific to Gargoyle, but happens with any Qt program on Wayland on Fedora.

Qt includes code to force X11 on Gnome, even under Wayland, with the comment:

> In Qt 5.11.0, support for selecting a platform plugin based
on the XDG_SESSION_TYPE environment variable was added. On gnome-shell, however,
bugs—in both Qt and gnome-shell—made many widget applications almost unusable.
So until those bugs are fixed XDG_SESSION_TYPE=wayland is now ignored on
gnome-shell.

See https://bugreports.qt.io/browse/QTBUG-68619 and https://github.com/qt/qtbase/commit/36d2ef5af9875afd9d398f5e37102194040cb1d9.

Fedora patches this out, and forces the Wayland backed on Gnome.  That's probably a bad idea given that Qt knows there are issues, but there you have it.  It's likely that Fedora's patch is the source of the problem.

The SRPM is available at https://rpmfind.net/linux/RPM/fedora/devel/rawhide/x86_64/q/qt5-qtbase-5.15.2-18.fc35.i686.html. This includes a patch called `qtbase-use-wayland-on-gnome.patch` which re-enables Wayland.

**Comment by speachy** [comment] 2021-06-16 10:32
$ ./bocfel I-0.z5 
QSocketNotifier: Can only be used with threads started with QThread
fatal: FT_New_Face: LuxiMonoRegular: 0x1Aborted (core dumped)

If I build garglk with BUNDLEFONTS = no, this problem goes away.  

In either case, the gisual problems are gone with this QT port!

**Comment by cspiegel** [comment] 2021-06-16 18:32
> fatal: FT_New_Face: LuxiMonoRegular: 0x1Aborted (core dumped)

Ok!  So I'm guessing you have a `.garglkrc` file that has entries like `monor LuxiMonoRegular`; this would be from an older Gargoyle installation.  Luxi Mono used to be the built-in monospace font, but it's been replaced.  Fonts in general on Gargoyle are Byzantine, and it doesn't help that the error message is pretty useless, and just dumped to stderr.

So the "fix" here is to add "propfont" and "monofont" entries to your `garglkrc` file which name fonts that exist on your system, and to ensure no `propr`- and `monor`-style entries exist.

I have a branch with _some_ font cleanup, but as with all of Gargoyle's config, it's not particularly user-friendly still.  It would be incredibly nice to have a configuration system that's easier to use, but that's easier said than done.

I did create #446 to add a message box on error so at least there's something useful to show the user.

> In either case, the gisual problems are gone with this QT port!

That's great to hear; thanks again for testing this!

As for the QSocketNotifier error... everything still seems to run OK even in the face of that.  I don't know who's not getting their socket notified, but Gargoyle doesn't have anything to do with sockets in Qt, so it probably only affects something in the Wayland backend, and maybe it's entirely benign: it seems to be from my testing, at least.

**Comment by cspiegel** [comment] 2021-06-19 02:08
Clossing as a result of the Qt port fixing visual glitches.  If bugs pop up they can be reported as new issues.

**Closed by cspiegel** 2021-06-19 02:08 UTC
