### ISSUE TITLE
glk_request_line_event() doesn't work on TextGrid windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#205] opened 2015-03-22 07:54 UTC
```
The following line causes a fatal error when "win" is a TextGrid window:

  glk_request_line_event(win, buffer + WORDSIZE, INPUT_BUFFER_LEN - WORDSIZE, 0);

The error message is:

  Glulxe fatal error: Mismatched array argument in Glk call.

However, it works OK when "win" is a TextBuffer window.

```

Original issue reported on code.google.com by `ricp...@gmail.com` on 22 Apr 2013 at 8:36

**Comment by cspiegel** [comment] 2017-04-18 01:33
I can't reproduce this directly (i.e. by writing a small standalone Glk program), and while the error message is coming from Glulxe, I can't fine a matching glk_request_line_event() call in the current Glulxe source.

As such I'm going to close this as “can't reproduce”.  If there's a Glulx game out there in which this can be reproduced, I'll take a look at it.

**Closed by cspiegel** 2017-04-18 01:33 UTC
Labels: auto-migrated, Priority-Medium, Type-Defect
