### ISSUE TITLE
gargoyle-free seems borked on Linux

### ISSUE THREAD

**Issue by ltallen** [garglk/garglk#822] opened 2024-02-25 05:54 UTC
I realize that a github issues page is not precisely the same thing as a support forum, but it's the closest I could find. I used Gargoyle years ago with no problem, and recently felt the urge to get back into IF.

I am running Ubuntu 23.10, and am using the gargoyle-free 2023.1 package from the Ubuntu universe repository. Whenever I try to run a non-Z Machine game (whether from Nautilus, from the prompt opened by running gargoyle from the dashboard, or from the terminal, I get the following error message: `fatal: Unable to find font Go Mono for Mono Regular, and fallback Gargoyle-Mono.ttf not found`. This despite the facts that a) Go Mono is indeed installed, since its package is a dependency and b) ~/.garglkrc has Liberation Mono as its monospace font. When I try to run a Z-Machine game, I get the error `Could not start interpreter /usr/libexec/gargoyle/frotz`. Indeed, there is no such file at that path, but my impression from one of the messages shown while installing the package is that Gargoyle interprets Z-code directly, and that the programs in /usr/libexec/gargoyle/ are for proprietary freeware interpreters that can be redistributed with Gargoyle but not incorporated into it? So it shouldn't need the Frotz interpreter, right?

This problem persisted on two separate computers, both running Ubuntu 23.10.

**Comment by cspiegel** [comment] 2024-02-25 15:01
I will install Ubunto 23.10 in a VM to see what's going on, but the reference to frotz indicates a possible rogue config file overriding the default interpreter.  Can you run the following:

```
gargoyle --paths /path/to/game.z5
```

And for all config files that it finds, see if any contain the string "frotz".

I say this because frotz has not been a part of Gargoyle for _years_, so shouldn't be referenced at all.  It may be that you have an older config file that's asking to use it.

As for the interpreters, `/usr/libexec/gargoyle` is in fact for _all_ interpreters.  The `gargoyle` binary is really just a launcher that starts one of the interpreters in that directory.  So it's normal for it to look there.

Regarding fonts, the fact that it's looking for Go Mono instead of your specified font also indicates some unwanted config file being loaded from somewhere. The fact that it can't load a fallback font indicates a packaging problem. I'm looking at the source for the package, and it's got a patch to _not_ install the fonts. So that's on Ubuntu (or rather Debian) for breaking things.

**Comment by cspiegel** [comment] 2024-02-25 15:55
I got Ubuntu 23.10 installed and testing indicates the following:

* Gargoyle works by default on a clean install.
* If you specify an invalid font in your config file, then you get the "unable to find font" message, which is a direct result of the package intentionally not installing the fallback fonts.
  * Your configuration, somehow, includes a font that can't be found, triggering this.
* The Unicode fallback font isn't installed, either, and due to a bug in 2023.1, without the fallback, a missing glyph will cause Gargoyle to crash (this is unrelated to your problem, but is an artifact of not installing any fonts by the package).

For _you_, the quick and dirty solution is to create the directory `/usr/share/fonts/gargoyle` and put the `fonts/Gargoyle-*` fonts from this repository in there.  That'll install the fallback fonts so at least Gargoyle will run. But better would be to first figure out why your config is not being honored.

My recommendations to the Debian packager:

* Gargoyle _needs_ to know the paths of fallback fonts.  If you don't want its fonts in `/usr/share/fonts`, then you can place them in `/usr/share/io.github.garglk/Gargoyle` and modify `font_path_fallback_system` in `garglk/draw.cpp` to unconditionally look for them there. If you really want system fonts to be the fallback instead, modify the `gli_initialize_fonts` function to include whatever fonts you want, ensuring that `font_path_fallback_system` is looking in the right place for them.
  * Gargoyle used to embed fonts in the binary so that fallback fonts _always_ worked. But the fonts it was using lacked decent Unicode coverage, and almost all modern fonts use the SIL Open Font License which does _not_ allow embedding in a GPL program. So Gargoyle now has to find fonts externally. If a user specifies an invalid font, Gargoyle will look for its fallback fonts, and if it can't find them, it aborts.
* Either install Gargoyle's Unifont fonts (which by default go into `/usr/share/io.github.garglk/Gargoyle`, so shouldn't interfere with anything), or make the system's unifont package a dependency, and modify `make_substitution_fonts` to point to the system unifont.

**Comment by ltallen** [comment] 2024-02-26 00:41
Alright, I figured it out. It was ~/.garglkrc. After reading your posts, I searched that file for the string "frotz", and sure enough it was there. When I deleted this file from my homefolder, everything started running properly. It may be that I have that file left over from when I used Gargoyle years ago (I backed up and restored my home folder from that install), but it doesn't explain why my laptop, which has a very-nearly clean install and definitely no years-old config files, had the same problem. It may be that the debian package includes a bad default ~/.garglkrc.

Thank you for the quick and detailed response. Great to see that this program is still being supported after so many years. In hindsight, I apologize for the overly alarmist title. Should have said it was borked *for me.*

**Comment by a-detiste** [comment] 2024-05-05 19:37
Hi, I will look into this. I did the last upload fro Debian but don't play the game myself. The usual quickfix is to add symlinks in the game dir that point to fonts in usr/share/... ; but this problem is worth a longuer investigation.

**Comment by a-detiste** [comment] 2024-05-05 19:40
I'll have to read this https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851111

**Comment by a-detiste** [comment] 2024-05-05 19:41
And this  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=743897 ...

**Comment by cspiegel** [comment] 2024-05-05 22:56
The font licensing issue is now moot: Gargoyle ships with three fonts: Charis SIL, Go Mono, and GNU Unifont. It no longer ships any GPL fonts.

Charis SIL and GNU Unifont are both licensed under the SIL Open Font License, and Go Mono is under the Go license, which is BSD-like.  No GPL licensed fonts are included (no _exclusively_ GPL font, anyway, since Unifont is dual licensed).

As for using fontconfig to look up fonts, it's an incorrect assumption that fontconfig's fallback will cause Gargoyle to find a font even when the user's specified font is not found.  Gargoyle will _not_ use fontconfig to find fallback fonts. It hard-codes its fallback font locations so that it has control over _which_ fonts are default.  So for fallback to work, Gargoyle's fonts need to be installed, or Gargoyle needs to be patched to look up _other_ fonts, which then must be dependencies for Gargoyle.

**Comment by cspiegel** [comment] 2024-05-30 13:37
Closing because this has been reported upstream; this is not a bug in Gargoyle itself.

**Closed by cspiegel** 2024-05-30 13:37 UTC
