### ISSUE TITLE
Script Recording Fails (TADS)

### ISSUE THREAD

**Issue by midiguru23** [garglk/garglk#657] opened 2022-07-09 22:57 UTC
I'm about to start beta-testing for a TADS 3 game. In the latest release of Gargoyle in Windows 10, script recording (the command 'script' opens a dialog box for saving the script file, but it then consistently reports, "Failed; an error occurred opening the script file."

Needless to say, this is a fatal error with respect to testing! Can it be fixed quickly? Hope so.

**Comment by cspiegel** [comment] 2022-07-11 03:56
I can't reproduce this.  Any chance you're using a filename that contains non-ASCII characters?  There was a bug related to that on Windows that's been fixed, but not in a release yet.  I'm attaching a build of the latest release branch which does have that fix (as well as a fix for a specific transcript writing bug that'll probably bite you if/when you get transcripting working...)

I keep meaning on releasing an update to 2022.1, and that probably should happen soon.

[gargoyle-2022.1-windows-i686.zip](https://github.com/garglk/garglk/files/9080796/gargoyle-2022.1-windows-i686.zip)
[gargoyle-2022.1-windows-x86_64.zip](https://github.com/garglk/garglk/files/9080799/gargoyle-2022.1-windows-x86_64.zip)

**Comment by cspiegel** [comment] 2022-12-21 01:43
Assuming this is fixed with the non-ASCII Windows fix.  If not, please reopen with more information.

**Closed by cspiegel** 2022-12-21 01:43 UTC
