### ISSUE TITLE
Visual artifacts in the text window

### ISSUE THREAD

**Issue by Nephar** [garglk/garglk#730] opened 2023-01-14 15:46 UTC
I see visual artifacts in the 2022.1 and 2023.1 RC for Mojave build. When scrolling the text window, dot artifacts appear on the left border. I believe the end of the hook of the capital letter "J" is culprit for this. The size of the artifact depends on the typeface used. Baskerville and Hoefler Text have the same issue. In all the affected typefaces(including mine, Fontin) the hook of capital "J" overflows under the preceding character. You can easily see that in Font Book app.
Another bit of information: The artifacts appear when scrolling the text window while there is that "J" present as the leftmost character on one line, and they are cleared away when I mouse click anywhere in the text window.

Here is a screenshot:
<img width="751" alt="Screen Shot 2023-01-14 at 06 29 12" src="https://user-images.githubusercontent.com/122389007/212480370-2fc68707-5eaa-4eb1-86ed-52549c4f83f0.png">

This is my [config file](https://drive.google.com/file/d/1VgP3Zg87oEEAkKb2w_9lRI9eRiWR2sFn/view?usp=share_link), and the font Fontin in the screenshot is provided by the designer and owner of the copyright free for personal use in his [website](https://www.exljbris.com/fontin.html).

**Comment by angstsmurf** [comment] 2023-01-14 18:08
A way to illustrate what is going wrong here is to set `wmarginx`  _and_ `tmarginx` to 0. No more artefacts! But now the characters are partly cut off by the window edge instead.

**Comment by Nephar** [comment] 2023-01-14 19:29
I see. Since the artifacts disappear when a mouse click event is registered, this suggest that the entire frame seems to be redrawn as opposed to a partial redraw during scrolling, right?

**Comment by angstsmurf** [comment] 2023-01-14 20:36
Yes, but partial redraws are probably fine as long as we add some extra horizontal padding at the margins.

**Comment by cspiegel** [comment] 2023-02-10 23:33
I don't have a fix for this, but I _do_ have an ugly workaround.  It works for me on Linux and Mac.  There's an unsigned Mac build here: https://github.com/cspiegel/garglk/actions/runs/4148464331

You have to add `redraw_hack 1` to your config file. That will cause it to redraw the whole screen a lot more frequently, which is just a band-aid, but should make things look better, at least.

With luck I'll get a proper fix in at some point, but for now, see if this one works for you.

**Comment by Nephar** [comment] 2023-02-11 14:56
Thank you for addressing this. I can not test it unfortunately, still on Mojave (Segmentation fault 11).

**Comment by cspiegel** [comment] 2023-02-11 18:20
Right, forgot you were on Mojave; I'm attaching a build I just did on Mojave that should work for you: [gargoyle-2023.1-mac.dmg.zip](https://github.com/garglk/garglk/files/10714402/gargoyle-2023.1-mac.dmg.zip)

**Comment by Nephar** [comment] 2023-02-11 20:27
First of all, I am grateful for the special build, I really am loath to burden you with my old OS.

The artifacts are in fact gone now. But if I am not mistaken the lag with the quick successive scroll inputs got worse slightly. But that lag was an issue since 2022.1 release anyway, I can live with that. I wonder if it is my system or do you happen to experience it as well?

**Comment by cspiegel** [comment] 2023-02-11 20:57
This hacky approach will be a bit slower (whether it's noticeable depends on how fast your computer is, I suppose), because it redraws more frequently.  Hopefully I'll get an appropriate fix in at some point, and remove `redraw_hack`.

As for lag, I haven't noticed anything, and offhand I can't think of any reason 2022.1 would be significantly different than 2019.1.  But if you'd like to open an issue here about it, go ahead, and I can try to reproduce it better.  If it's a Mac-only thing, it'll be harder for me, since I run all my Mac stuff in VMs, meaning performance issues I see can't easily be attributed to Gargoyle itself vs running in a virtualized environment.

**Comment by Nephar** [comment] 2023-02-11 23:06
I will open an issue about the lag once I gather some more data about it, thank you.

**Closed** 2023-02-22 02:52 UTC
