### ISSUE TITLE
speak_input 0 setting is not working

### ISSUE THREAD

**Issue by Durafen** [garglk/garglk#356] opened 2019-11-12 14:38 UTC
while speak_input is 0, garglk is still reading the user input.
I'm using macOS 10.13

Image with my TTS setting:
https://take.ms/wyWfIv

Is this a bug, or i am doing something wrong with the settings?

**Comment by cspiegel** [comment] 2019-12-07 17:51
It's not a bug per se, but it's definitely not intuitive behavior.

The issue is that when your input appears on the screen, it's not directly the text you typed.  Gargoyle does something like this internally during line input:

1. Allow the user to type, displaying the text as he types
2. Once ENTER is hit, erase all the text the user typed
3. If the current window is configured to echo the user's text, reprint it

`speak_input` lives somewhere in between steps 1 and 2.  If it's turned on, the typed-in text will be spoken as the text is being erased.  Then, the text is printed again in step 3, and since this isn't input text anymore, it's spoken again.  Of course logically it *is* input text, but that's not what `speak_input` is referring to.

So even if you have `speak_input` off, step 3 runs, and the text is printed.  And it's not as easy as just moving the `speak_input` test to step 3 (i.e., if `speak_input` is off, then just turn off TTS while reprinting the input text), because interpreters can (and at least Bocfel does) turn off echoing, and then print out the input text manually.  At that point, Gargoyle can't reliably figure out what text it should not speak.

There is a potential workaround, but it may have pitfalls.  Glk (and so Gargoyle) has the ability to style text printed to the screen.  When user input is requested, then the *input* style is enabled.  Moreoever, Bocfel also turns on *input* styling when reprinting text, so that it still has the appearance of being echoed by Gargoyle itself.  I can modify things so that `speak_input`, instead of operating in terms of directly-typed text, instead operates in terms of “indirectly-typed” text, so-to-speak, by disabling TTS whenever *input* styling is active.

Interpreters could of course set *input* style whenever they pleased, e.g. during regular game play, which would mean no text gets spoken.  This isn't a real problem because Gargoyle bundles interpreters so we can be sure that doesn't happen.

A more serious concern is that Glulx games can control Glk styles, so it'd be perfectly valid for a game to set the *input* style and print some in-game text, for example if a game wanted to drop you into the middle of the action, pretending you had already been playing (such as in *Plundered Hearts*).  I have absolutely no idea how many games set _input_ styling themselves.

I don't know the best approach.  I lean toward `speak_input` turning off TTS when _input_ styling is active.  For those who need their text echoed, and who turn `speak_input` on, this would provide almost no change.  For those who do not want text spoken, it would prevent all (or almost all) input text from being spoken, but might also prevent some other text as well.

**Comment by cspiegel** [comment] 2021-10-20 17:42
I've got a proposed fix at #515.

This is the "don't speak input styled text" as mentioned above. It has the drawback that if a game/interpreter sets the input style for text not entered by the user, it won't get spoken.

But this does mean that `speak_input 0` will turn off all input, and has the nice side effect of preventing doubled-up input being spoken by Bocfel when input speech is enabled.

The only way to fix this entirely, from what I see, is to add a way to differentiate user input vs generated text when `style_Input` is used.  That'd require a new custom style or API call.  I can do that but I'd rather avoid it if possible, so we can at least explore the solution in #515.

**Comment by cspiegel** [comment] 2021-11-07 02:18
This has been merged in.

**Closed by cspiegel** 2021-11-07 02:18 UTC
