### ISSUE TITLE
2011.1 for Mac selects wrong font

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#146] opened 2015-03-22 07:53 UTC
```
What steps will reproduce the problem?
1. The problem is intermittent, I haven't found a trigger.
2. Open up any glulx game (other game types are probably also affected, but I 
haven't tested)

What is the expected output? What do you see instead?
The main text displayed should be Linux Libertine, a serif font. Instead, I see 
a larger, chunkier, sanserif bold italic. (Screenshot attached.) The fixed 
width font (status window) is unaffected.

What version of the product are you using? On what operating system?
2010.1, Mac

Please provide any additional information below.
Restarting the system or reinstalling Gargoyle will cause the font to display 
correctly; simply restarting the story file or the Gargoyle application does 
not.  This issue has occurred perhaps 3-4 times for me in the last 2 months or 
so. The cause is unclear.
```

Original issue reported on code.google.com by `Ek.Temple@gmail.com` on 14 Apr 2011 at 2:28

Attachments:
- [Screenshot.png](https://storage.googleapis.com/google-code-attachments/garglk/issue-146/comment-0/Screenshot.png)

**Comment by cspiegel** [comment] 2021-11-08 06:44
Nobody seems to have reported this for ages, and I can't reproduce it, so closing this.

**Closed by cspiegel** 2021-11-08 06:44 UTC
Labels: Type-Defect, auto-migrated, Priority-High
