### ISSUE TITLE
Missing splash screen in Aisle

### ISSUE THREAD

**Issue by salty-horse** [garglk/garglk#662] opened 2022-07-15 09:55 UTC
This is very odd.

When I try running [Aisle](https://ifdb.org/viewgame?id=j49crlvd62mhwuzu) in the latest Gargoyle I don't see the "splash screen". It's a text box that appears when you start the game and gives an introduction that starts with "You are about to read a story". Instead, there's a blank screen that I dismiss by pressing Enter.

It appears fine when I use Frotz 2.53. Is this a regression?

**Comment by cspiegel** [comment] 2022-07-18 03:40
This is a bug in *Aisle* which manifests ifself when your column count is less than 70 (actually it's broken up to 74, but at least the text is visible from 70-74).  Things only start working properly at 75.

*Aisle* wants its splash screen to be a box of width 75, and wants it to be centered, no matter what, even if it wouldn't fit on the screen.  The code does something like this (see routine d810 in a disassembly):

```
pos = get_screen_width() - 71
pos = (pos / 2) - 2;
set_cursor(4, pos)
```
The problem is that for all screen widths 74 and less, `pos` becomes negative (and actually, 75 is technically illegal too, since that results in a value of 0, and the origin is at (1,1); but Bocfel rewrites 0 to 1 because at least *Paint and Corners* assumes it's valid).

So anyway, the default column size for Gargoyle is 60.  That gives ((60 - 71) / 2) - 1 = -7 or, if interpreted as unsigned, 65529

§8.7.2.3 of the Standard says this: “It is illegal to move the cursor outside the current size of the upper window.”

Whether or not this value ought to be interpreted as signed or unsigned is irrelevant here, as both -7 and 65529 are outside the upper window.

After all that I got to thinking, and figured it might be a bug in Inform's "box" command, and indeed, that seems to be the case. The same thing happens with Curses, though it requires a much narrower window, since its box is narrower.

I'm somewhat inclined to treat this as signed, and if it's negative, pretend it's 1. Alternatively *any* value that's too large could be pulled to zero.  It's a violation of the Standard in either case, so the game can't complain.

I've also posted a note on this to the IF forum: https://intfiction.org/t/bug-in-inform-6s-box-statement/56884

**Comment by salty-horse** [comment] 2022-07-18 06:25
Thanks. Maybe this should be added to the default settings file, as it already includes tweaks for several games:
```
[ Aisle.z5]
cols 75
```

**Comment by cspiegel** [comment] 2022-08-01 22:56
> Thanks. Maybe this should be added to the default settings file, as it already includes tweaks for several games:
> 
> ```
> [ Aisle.z5]
> cols 75
> ```

This is indeed a bug in Inform.  It very probably affects a boatload of games (any which use "box", really).  As such I don't think per-game settings are tenable here.  The bug is that Inform tries to position the cursor outside the screen (to a negative position), which is invalid and thus has undefined behavior.  I've added a workaround to Bocfel which simply rewrites all negative values to 1 (the left-most column), which is an extension of an existing workaround for games that think (0,0) is the origin.

I'll get the fix into Gargoyle before the next release.

**Comment by cspiegel** [comment] 2022-12-21 01:43
Updated to the latest Bocfel, so the fix is here now.

I also pushed a fix (workaround, really) to Inform, so hopefully newer games won't have this behavior.

**Closed by cspiegel** 2022-12-21 01:43 UTC
